const formatVisionResponse = require('../formatVisionResponse')

const vision = [
    "COSTCO.",
    "EWHOLESALE",
    "Costco #12 06",
    "1641 Pine Plaza Dr",
    "Apex, NC 27523",
    "Member#",
    "111847464945",
    "Invoice#",
    "62811",
    "Date:",
    "04/23/20",
    "Time:",
    "09:59",
    "Auth#",
    "02445D",
    "UI Acct",
    "%23",
    "************1444",
    "Pump",
    "Gallons",
    "Price",
    "4.771",
    "$ 1.459",
    "Product",
    "Amount",
    "Regular",
    "$ 6.96",
    "Total Sale",
    "$ 6.96",
    "SALE-",
    "Card Swiped",
    "Approved",
    "TranID# 011403 062811",
    "Thank you",
    "For your purchase of",
    "Kirkland Signature",
    "Fuel",
    "Visit Costco.com",
    "Search: Fuel"
]

console.log(formatVisionResponse(vision))